version: '3.8'

services:
  webapp:
    build:
      context: .
    container_name: app
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: data_kepegawaian
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_kepegawaian
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
